### ISSUE TITLE
Where is SutControlAdapter.GetNumberOfAddressBookObject() defined?

### ISSUE THREAD

**Issue by st-gwerner** [OfficeDev/Interop-TestSuites#26]
Where is the GetNumberOfAddressBookObject() function implemented?

Example usage under MSOXNSPI_S02_TC11_SeekEntriesSuccessWithNullTable:

`uint objectNum = this.SutControlAdapter.GetNumberOfAddressBookObject();`

I found an interface in IMS_OXNSPISUTControlAdapter, but cannot find the actual code that runs to get the count.

**Comment by tomjebo** [comment]
@st-gwerner the GetNumberOfAddressBookObject() method is in the SUT Control Adapter as you found. It's not implemented in C# because there is a PowerShell script implementation instead. The C# interface implementation is mapped to the ps1 file under the "Implementation" folder via the PTF (Protocol Test Framework) feature for creating the adapter. Please see the PTF documentation for more information: [Protocol Test Adapters](https://github.com/Microsoft/ProtocolTestFramework/blob/master/docs/PTFUserGuide.md#-protocol-test-adapters)

**Comment by st-gwerner** [comment]
Thanks!
