### ISSUE TITLE
Put Changes - Favor Coherency Failure Over Not Found

### ISSUE THREAD

**Issue by benerobert** [OfficeDev/Interop-TestSuites#93]
Hi!

At the end of the 'TestCase_S13_TC01_PutChanges_ValidExpectedStorageIndexExtendedGUID' test case, the check expects a 'Referenceddataelementnotfound' error.

![image](https://user-images.githubusercontent.com/128474016/232433422-84cc71c7-bf2e-4ff1-87e1-4797d3aed717.png)

However, according to MS-FSSHTTPB 2.2.2.1.4, if the 'Favor Coherency Failure Over Not Found' flag is set to 1, then a 'Coherency Failure' error should be returned. That is, it is not clear because it says: 'A bit that specifies to force a coherency check on the server, if a Referenced Data Element Not Found failure occurred. This **might** result in a Coherency Failure returned instead of Referenced Data Element Not Found.'

In the current test case, this flag is set to 1:
![image](https://user-images.githubusercontent.com/128474016/232434815-f2017724-0ed0-44a7-bf34-d7a61c49e18b.png)

Can you tell me what exactly you mean by coherency check?

**Comment by JimZhao2023** [comment]
@benerobert Actually TestCase_S13_TC08_PutChanges_FavorCoherencyFailureOverNotFound is used to test "A bit that specifies to force a coherency check on the server, if a Referenced Data Element Not Found failure occurred. This might result in a Coherency Failure returned instead of Referenced Data Element Not Found." in MS-FSSHTTPB 2.2.2.1.4. But based on our test result against SharePoint env, it always returns referenceddataelementnotfound instead of coherency failure error. In the spec, it uses the keyword "might" instead of "must", so, strictly speaking, it also meets the spec even though it returns referenceddataelementnotfound. 

And for the code snippet you mentioned, at the end of the 'TestCase_S13_TC01_PutChanges_ValidExpectedStorageIndexExtendedGUID' test case, it is used to test "If the Extended GUID does not have the corresponding data element in the Data Element Package of the request, the protocol server MUST return a Cell Error failure value of 16 indicating the referenced data element not found failure, as specified in section 2.2.3.2.1.", because it set null to data elements in put change request in line 118. So, it is correct to return referenceddataelementnotfound.
cellRequest.AddSubRequest(putChange,  null); 

Please let me know if you have any other questions.

**Comment by JimZhao2023** [comment]
@benerobert do you have any other questions? If everything is okay, could you please close this issue? Thank you so much.
